' https://www.chronoscan.org/doc/export_zone_bitmap_from_a_capture_grid_control_after_export_with_vbscript.htm?q=c2NyaXB0&ms=AAAAAAAAAA==&mw=NDcx&st=Mg==&sct=MA==

Function GetPath(file)
    Dim objFSO, objFile, objFolder
    Dim intIndex
 
    Set objFSO = CreateObject("Scripting.FileSystemObject")
    Set objFile = objFSO.GetFile(file)
    Set objFolder = objFile.ParentFolder
 
    GetPath=objFolder.Path
End Function
 
Set Batch = ChronoApp.GetCurrentBatch
    
Dim NumDocs
NumDocs=Batch.GetDocCount
 
'navigating records
For numDoc = 0 To NumDocs-1
    If (Batch.IsValidated(numDoc)) Then
        'we need the path of a file generated by xml export module
 'when the document has exported, the system field "expinfo.XML Report.File Sysstem_1" is filled with the generated xml
 'we can use it to extract the path to save the bmp in the same directory
        Dim strPath
        strPath = Batch.GetSystemField (numDoc, "expinfo.XML Report.File System_1")'first part of a result bmp
        strPath=GetPath(strPath)'we need Only file path
        Dim Barcode1
        Barcode1 = Batch.GetUserField( numDoc, "Barcode 1")'Second part of a result bmp
        'MsgBox "Document Barcode1: "+Barcode1
 
          
 
        Dim tableNumber, numRows
        tableNumber=1'we are using table 1
 
        numRows=Batch.GetXgridRowCount (numDoc,tableNumber)
        MsgBox "Total Records in xgrid table: "  + CStr(numRows)
       
        'navigating xgrid table records
        Dim row
        For row = 0 To numRows-1
 
            'Extract field "ID" from xgrid For compose export bmp file
            Dim strIndexValue
 
           
            strIndexValue=Batch.GetXgridFieldValue (numDoc,tableNumber, row, "Index")'Third part of a result bmp
       
            Dim strSaveFile
            strSaveFile=strPath+"\"+Barcode1+"_"+strIndexValue+".bmp"
            'MsgBox "File to save: "+strSaveFile
            If Batch.GetXgridFieldBitmap (numDoc,tableNumber, row, "Signature", strSaveFile) Then
            Else
               MsgBox "An Error occurred saving file: " +strSaveFile
               Exit For
            End If
        Next
    End If
Next

